version: "3.9"
services:
  web:
    build: .
    ports:
      - "12515:80"
    volumes:
      - .:/src
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - .:/data/db
    ports:
      - "21551:27017"